"use client";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
// Task 97.4 (Этап 4, spec_max_graf_fix.md §8): тиражирование раскрытия
// графиков. Корень Обзора: relative всегда (правка A), overflow переключается
// по expandedChartId (правка C); графические представления (включая
// HTML-теплокарту корреляций) обёрнуты в ExpandableChartPanel (§7.2),
// таблица решений — без панели. Панель «Granger» — только при наличии
// данных (прецедент Этапа 2). detail_level не заказан (Этап 5 опционален).
import { ExpandableChartPanel } from "./ExpandableChartPanel";
import { ExpandableChartsProvider } from "./ExpandableChartsProvider";
import { useExpandableChartState } from "../hooks/useExpandableChart";

export type FeatureDecision = "keep" | "review" | "low_signal";
export interface EdaFeatureSelectionItem { name:string; n_observations:number; pearson:number; spearman:number; vif:number|null; vif_infinite:boolean; max_abs_predictor_correlation:number; granger_available:boolean; best_granger_lag:number|null; granger_p_value:number|null; granger_adjusted_p_value:number|null; granger_significant:boolean; decision:FeatureDecision; decision_reason:string }
export interface EdaFeatureSelectionResponse { column:string; applicable:boolean; applicability_status:"applicable"|"not_required"|"requires_preprocessing"|"not_applicable"; reason:string|null; n_observations:number; min_observations:number; numeric_candidates:number; analyzed_features:number; alpha:number; requested_max_lag:number; max_lag:number; correlation_threshold:number; vif_threshold:number; difference_order:0|1; granger_n_observations:number; granger_available:boolean; granger_reason:string|null; order_source:"time_column"|"row_order"; order_column:string|null; order_warning:string|null; frequency:string|null; correlation_matrix:Array<{row:string;column:string;pearson:number;spearman:number}>; features:EdaFeatureSelectionItem[]; granger:Array<{feature:string;lag:number;f_statistic:number;p_value:number;adjusted_p_value:number;significant:boolean}>; high_correlation_pairs:Array<{first:string;second:string;correlation:number}>; excluded_features:Array<{name:string;reason:string}>; kept_features:string[]; review_features:string[]; low_signal_features:string[]; recommendation:string|null; recommendations:string[]; warnings:string[] }
export interface EdaFeatureSelectionParameters { alpha:number; maxLag:number; correlationThreshold:number; vifThreshold:number; differenceOrder:0|1 }
interface Props { profile:EdaFeatureSelectionResponse|null; loading:boolean; error:string|null; noDataset:boolean; parameters:EdaFeatureSelectionParameters; onParametersChange:(changes:Partial<EdaFeatureSelectionParameters>)=>void }
type View="association"|"matrix"|"vif"|"granger"|"decision";
const tabs:Array<{id:View;label:string}>=[{id:"association",label:"Связь с Y"},{id:"matrix",label:"Матрица"},{id:"vif",label:"VIF"},{id:"granger",label:"Granger"},{id:"decision",label:"Решение"}];
const fmt=(v:number|null|undefined,d=4)=>v==null||!Number.isFinite(v)?"—":v.toLocaleString("ru-RU",{maximumFractionDigits:d});
function Select({label,value,options,onChange}:{label:string;value:number;options:Array<{value:number;label?:string}>;onChange:(n:number)=>void}) { return <label className="text-[10px] text-neutral-500"><span className="block">{label}</span><select aria-label={label} value={value} onChange={e=>onChange(Number(e.target.value))} className="rounded border px-1 py-1 text-xs">{options.map(o=><option key={o.value} value={o.value}>{o.label??o.value}</option>)}</select></label> }
export function EdaFeatureSelectionOverview(props:Props){
 return (
  <ExpandableChartsProvider>
   <EdaFeatureSelectionOverviewInner {...props} />
  </ExpandableChartsProvider>
 );
}
function EdaFeatureSelectionOverviewInner({profile,loading,error,noDataset,parameters,onParametersChange}:Props){
 const [view,setView]=useState<View>("association"); const [method,setMethod]=useState<"pearson"|"spearman">("pearson"); const {expandedChartId}=useExpandableChartState();
 if(loading)return <div role="status" className="flex h-[468px] items-center justify-center">Сопоставляем связь с целью, VIF и Granger…</div>;
 if(error)return <div role="alert" className="flex h-[468px] items-center justify-center text-red-700">{error}</div>;
 if(noDataset)return <div role="status" className="flex h-[468px] items-center justify-center">Загрузите датасет, чтобы выполнить отбор признаков.</div>;
 if(!profile)return <div role="status" className="flex h-[468px] items-center justify-center">Выберите числовой исследуемый признак Y.</div>;
 if(!profile.applicable){
  const neutral=profile.applicability_status==="not_required";
  const content=<><h4 className="text-sm font-semibold">{neutral?"Отбор признаков не требуется":"Предикторы требуют подготовки"}</h4><p className="mt-2 text-sm">{profile.reason}</p>{neutral&&<p className="mt-2 text-xs text-neutral-600">Одномерный ряд можно передавать в модели, использующие лаги самой цели, тренд и сезонность.</p>}{profile.excluded_features.length>0&&<div className="mt-4 w-full max-w-2xl text-left"><p className="mb-2 text-xs font-semibold">Исключённые кандидаты</p><ul className="space-y-2">{profile.excluded_features.map(item=><li key={item.name} className="rounded border border-amber-200 bg-white p-2"><span className="font-medium">{item.name}</span><span className="ml-2 text-xs">{item.reason}</span></li>)}</ul></div>}</>;
  return neutral?<section role="status" className="flex h-[468px] flex-col items-center justify-center rounded-lg bg-neutral-50 px-8 text-center text-neutral-700">{content}</section>:<section role="alert" className="flex h-[468px] flex-col items-center justify-center overflow-y-auto rounded-lg bg-amber-50 px-8 text-center text-amber-900">{content}</section>;
 }
 const data=profile.features; const names=Array.from(new Set(profile.correlation_matrix.map(x=>x.row))); const pairs=new Map(profile.correlation_matrix.map(x=>[`${x.row}\0${x.column}`,x]));
 return <section className={`relative flex h-[468px] min-h-0 flex-col rounded-lg border bg-white feed-scroll ${expandedChartId?"overflow-hidden":"overflow-y-auto"}`}>
  <div className="shrink-0 border-b p-4"><div className="flex justify-between gap-4"><div><h4 className="text-sm font-semibold">Отбор для Y = «{profile.column}»</h4><p className="text-xs text-neutral-500">n={profile.n_observations} · кандидатов {profile.analyzed_features} · Granger: {profile.difference_order?"первые разности":"текущие уровни"}</p></div><div className="flex flex-wrap justify-end gap-2"><Select label="Уровень значимости α" value={parameters.alpha} options={[.01,.05,.1].map(value=>({value}))} onChange={alpha=>onParametersChange({alpha})}/><Select label="Максимальный лаг" value={parameters.maxLag} options={[1,2,3,6,12].map(value=>({value}))} onChange={maxLag=>onParametersChange({maxLag})}/><Select label="Порог связи |r|" value={parameters.correlationThreshold} options={[.2,.3,.5,.7].map(value=>({value}))} onChange={correlationThreshold=>onParametersChange({correlationThreshold})}/><Select label="Порог VIF" value={parameters.vifThreshold} options={[5,10,20].map(value=>({value}))} onChange={vifThreshold=>onParametersChange({vifThreshold})}/><Select label="Ряд для Granger" value={parameters.differenceOrder} options={[{value:0,label:"Текущий"},{value:1,label:"Δ1"}]} onChange={differenceOrder=>onParametersChange({differenceOrder:differenceOrder as 0|1})}/></div></div>
  {profile.recommendation&&<p className="mt-2 rounded bg-brand-light p-2 text-xs">{profile.recommendation}</p>}{profile.warnings.length>0&&<p className="mt-2 rounded bg-amber-50 p-2 text-xs text-amber-800">{profile.warnings.join(" ")}</p>}</div>
  <div role="tablist" aria-label="Представления отбора признаков" className="flex shrink-0 gap-1 border-b px-4 pt-3">{tabs.map(t=><button key={t.id} role="tab" aria-selected={view===t.id} onClick={()=>setView(t.id)} className={`rounded-t px-3 py-2 text-xs ${view===t.id?"bg-brand text-white":"bg-neutral-50"}`}>{t.label}</button>)}</div>
  {view==="association"&&<ExpandableChartPanel chartId="feature-association" title="Связь признаков с целью"><div role="img" aria-label={`Связь признаков с целью ${profile.column}`} className="min-h-0 flex-1 p-3"><ResponsiveContainer><BarChart data={data} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" domain={[-1,1]}/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Legend/><Bar dataKey="pearson" fill="#2563eb" isAnimationActive={false}/><Bar dataKey="spearman" fill="#7c3aed" isAnimationActive={false}/></BarChart></ResponsiveContainer></div></ExpandableChartPanel>}
  {view==="matrix"&&<ExpandableChartPanel chartId="feature-matrix" title="Матрица корреляций признаков"><div role="img" aria-label={`Матрица корреляций признаков для ${profile.column}`} className="min-h-0 flex-1 overflow-auto p-3"><div className="mb-2 text-right"><button onClick={()=>setMethod("pearson")} className="mr-1 text-xs">Pearson</button><button onClick={()=>setMethod("spearman")} className="text-xs">Spearman</button></div><div className="inline-grid min-w-full gap-1" style={{gridTemplateColumns:`100px repeat(${names.length},55px)`}}><div/>{names.map(n=><div key={`h${n}`} className="truncate text-[9px]">{n}</div>)}{names.flatMap(r=>[<div key={`r${r}`} className="truncate text-[9px]">{r}</div>,...names.map(c=>{const v=pairs.get(`${r}\0${c}`)?.[method]??0;return <div key={`${r}${c}`} title={`${r} × ${c}: ${fmt(v)}`} className="rounded p-2 text-center text-[9px] text-white" style={{backgroundColor:v>=0?`rgba(37,99,235,${.2+.7*Math.abs(v)})`:`rgba(220,38,38,${.2+.7*Math.abs(v)})`}}>{fmt(v,2)}</div>})])}</div></div></ExpandableChartPanel>}
  {view==="vif"&&<ExpandableChartPanel chartId="feature-vif" title="Диагностика VIF"><div role="img" aria-label={`Диагностика VIF для ${profile.column}`} className="min-h-0 flex-1 p-3"><ResponsiveContainer><BarChart data={data.map(x=>({...x,displayVif:x.vif_infinite?profile.vif_threshold*2:x.vif??0}))} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><ReferenceLine x={profile.vif_threshold} stroke="#dc2626"/><Bar dataKey="displayVif" isAnimationActive={false}>{data.map(x=><Cell key={x.name} fill={x.vif_infinite||(x.vif??0)>=profile.vif_threshold?"#dc2626":"#2563eb"}/>)}</Bar></BarChart></ResponsiveContainer></div></ExpandableChartPanel>}
  {view==="granger"&&(profile.granger_available?<ExpandableChartPanel chartId="feature-granger" title="Granger-доказательность"><div role="img" aria-label={`Granger X в ${profile.column} после FDR`} className="min-h-0 flex-1 p-3"><ResponsiveContainer><BarChart data={data.map(x=>({...x,evidence:x.granger_adjusted_p_value==null?0:-Math.log10(Math.max(x.granger_adjusted_p_value,1e-12))}))} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><ReferenceLine x={-Math.log10(profile.alpha)} stroke="#dc2626"/><Bar dataKey="evidence" isAnimationActive={false}>{data.map(x=><Cell key={x.name} fill={x.granger_significant?"#16a34a":"#a3a3a3"}/>)}</Bar></BarChart></ResponsiveContainer></div></ExpandableChartPanel>:<div role="status" className="flex min-h-0 flex-1 items-center justify-center p-8 text-amber-800">{profile.granger_reason}</div>)}
  {view==="decision"&&<div className="shrink-0 overflow-x-auto"><table aria-label="Рекомендации по признакам" className="w-full text-xs"><thead><tr><th>Признак</th><th>Pearson</th><th>Spearman</th><th>VIF</th><th>Granger q</th><th>Решение</th><th>Основание</th></tr></thead><tbody>{data.map(x=><tr key={x.name}><td>{x.name}</td><td>{fmt(x.pearson)}</td><td>{fmt(x.spearman)}</td><td>{x.vif_infinite?"∞":fmt(x.vif)}</td><td>{fmt(x.granger_adjusted_p_value)}</td><td>{x.decision==="keep"?"Сохранить":x.decision==="review"?"Проверить":"Слабый сигнал"}</td><td>{x.decision_reason}</td></tr>)}</tbody></table></div>}
 </section>
}
