import "@testing-library/jest-dom";
import {fireEvent,render,screen} from "@testing-library/react";
import {EdaFeatureSelectionOverview,type EdaFeatureSelectionResponse} from "./EdaFeatureSelectionOverview";
const item={name:"X",n_observations:100,pearson:.5,spearman:.4,vif:2,vif_infinite:false,max_abs_predictor_correlation:0,granger_available:true,best_granger_lag:1,granger_p_value:.01,granger_adjusted_p_value:.02,granger_significant:true,decision:"keep" as const,decision_reason:"Есть сигнал"};
const profile:EdaFeatureSelectionResponse={column:"Y",applicable:true,applicability_status:"applicable",reason:null,n_observations:100,min_observations:30,numeric_candidates:1,analyzed_features:1,alpha:.05,requested_max_lag:3,max_lag:3,correlation_threshold:.3,vif_threshold:5,difference_order:0,granger_n_observations:100,granger_available:true,granger_reason:null,order_source:"time_column",order_column:"Date",order_warning:null,frequency:"D",correlation_matrix:[{row:"Y",column:"Y",pearson:1,spearman:1},{row:"Y",column:"X",pearson:.5,spearman:.4},{row:"X",column:"Y",pearson:.5,spearman:.4},{row:"X",column:"X",pearson:1,spearman:1}],features:[item],granger:[],high_correlation_pairs:[],excluded_features:[],kept_features:["X"],review_features:[],low_signal_features:[],recommendation:"Сохранить X",recommendations:[],warnings:[]};
describe("EdaFeatureSelectionOverview",()=>{it("switches all five views",()=>{render(<EdaFeatureSelectionOverview profile={profile} loading={false} error={null} noDataset={false} parameters={{alpha:.05,maxLag:3,correlationThreshold:.3,vifThreshold:5,differenceOrder:0}} onParametersChange={jest.fn()}/>);expect(screen.getByRole("img",{name:/Связь признаков/})).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Матрица"}));expect(screen.getByRole("img",{name:/Матрица корреляций/})).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"VIF"}));expect(screen.getByRole("img",{name:/Диагностика VIF/})).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Granger"}));expect(screen.getByRole("img",{name:/Granger X/})).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Решение"}));expect(screen.getByRole("table",{name:"Рекомендации по признакам"})).toBeInTheDocument();});it("переключатели представлений следуют бейдж-паттерну «Обзора» «Предобработки»",()=>{render(<EdaFeatureSelectionOverview profile={profile} loading={false} error={null} noDataset={false} parameters={{alpha:.05,maxLag:3,correlationThreshold:.3,vifThreshold:5,differenceOrder:0}} onParametersChange={jest.fn()}/>);const tablist=screen.getByRole("tablist",{name:"Представления отбора признаков"});expect(tablist).toHaveClass("mt-3","flex","flex-wrap","gap-2");expect(tablist.parentElement).toHaveClass("p-4");expect(tablist.parentElement?.className).toContain("border-b border-neutral-100");const active=screen.getByRole("tab",{name:"Связь с Y"});expect(active).toHaveAttribute("aria-selected","true");expect(active).toHaveClass("rounded-full","border","px-3","py-1","text-xs");expect(active).toHaveClass("border-neutral-300","bg-neutral-200","text-neutral-800");const inactive=screen.getByRole("tab",{name:"Матрица"});expect(inactive).toHaveAttribute("aria-selected","false");expect(inactive).toHaveClass("rounded-full","border","px-3","py-1","text-xs");expect(inactive).toHaveClass("border-neutral-200","bg-neutral-50","text-neutral-500","hover:bg-neutral-100");});});

describe("feature-selection applicability states",()=>{
  it("shows a neutral message for a genuinely univariate series",()=>{
    render(<EdaFeatureSelectionOverview profile={{...profile,applicable:false,applicability_status:"not_required",reason:"Числовые предикторы X отсутствуют: отбор признаков не требуется.",features:[],analyzed_features:0,correlation_matrix:[],kept_features:[]}} loading={false} error={null} noDataset={false} parameters={{alpha:.05,maxLag:3,correlationThreshold:.3,vifThreshold:5,differenceOrder:0}} onParametersChange={jest.fn()}/>);
    expect(screen.getByRole("status")).toHaveTextContent("Отбор признаков не требуется");
    expect(screen.getByText(/одномерный ряд/i)).toBeInTheDocument();
  });
  it("lists every rejected predictor and its remediation reason",()=>{
    render(<EdaFeatureSelectionOverview profile={{...profile,applicable:false,applicability_status:"requires_preprocessing",reason:"Предикторы требуют подготовки.",features:[],analyzed_features:0,correlation_matrix:[],kept_features:[],excluded_features:[{name:"Amount",reason:"Нечисловой тип object."},{name:"Volume",reason:"Есть 2 пропуска."}]}} loading={false} error={null} noDataset={false} parameters={{alpha:.05,maxLag:3,correlationThreshold:.3,vifThreshold:5,differenceOrder:0}} onParametersChange={jest.fn()}/>);
    expect(screen.getByRole("alert")).toHaveTextContent("Предикторы требуют подготовки");
    expect(screen.getByText("Amount")).toBeInTheDocument();
    expect(screen.getByText(/Есть 2 пропуска/)).toBeInTheDocument();
  });
});
